import type { ShellState } from './controller-shell-state.js';

export type ControllerUiSyncState = Pick<
  ShellState,
  | 'runtime'
  | 'selectedSession'
  | 'selectedRun'
  | 'workspacePathDraft'
  | 'providerIdDraft'
  | 'sessionApprovalPolicyDraft'
  | 'sessionApprovalPolicyDraftDisabled'
  | 'promptDraftDisabled'
  | 'routingToolsDraft'
  | 'selectedSessionApprovalPolicyDraft'
  | 'selectedSessionApprovalPolicyDraftDisabled'
  | 'applySelectedSessionPolicyDisabled'
  | 'startRunDisabled'
  | 'routeRunDisabled'
  | 'delegateRunDisabled'
  | 'handoffRunDisabled'
  | 'resumeSessionDisabled'
  | 'cancelRunDisabled'
  | 'reviewRunDisabled'
  | 'verifyRunDisabled'
  | 'sessionProviderNoteMessage'
  | 'selectedSessionNoteMessage'
>;

export type ControllerRequesterState = Pick<
  ShellState,
  | 'runtime'
  | 'selectedSession'
  | 'workspacePathDraft'
  | 'providerIdDraft'
  | 'sessionApprovalPolicyDraft'
  | 'promptDraft'
  | 'routingToolsDraft'
  | 'delegateRoleDraft'
>;

export type ControllerRunActionState = Pick<
  ShellState,
  | 'runtime'
  | 'selectedSession'
  | 'selectedRun'
  | 'transcript'
  | 'recommendation'
  | 'sessions'
  | 'runs'
  | 'recentSessionsMessage'
  | 'promptDraft'
  | 'routingToolsDraft'
  | 'delegateRoleDraft'
  | 'workspacePathDraft'
  | 'providerIdDraft'
  | 'sessionApprovalPolicyDraft'
  | 'selectedSessionApprovalPolicyDraft'
  | 'selectedSessionApprovalPolicyDraftDisabled'
  | 'applySelectedSessionPolicyDisabled'
  | 'runModeDraft'
  | 'undoAvailable'
  | 'undoDetail'
  | 'orchestratorNoteMessage'
  | 'runStateNoteMessage'
  | 'runUpdateFeedbackMessage'
  | 'recommendationRequestToken'
>;

export type ControllerRuntimeSessionState = Pick<
  ShellState,
  | 'runtime'
  | 'toolPlane'
  | 'sessions'
  | 'recentSessionsMessage'
  | 'archiveSessions'
  | 'orchestrationFlows'
  | 'selectedSession'
  | 'runs'
  | 'workspacePathDraft'
  | 'providerIdDraft'
  | 'providerHealthMessage'
  | 'providerSessionLabel'
  | 'dataDirectoryLabel'
  | 'toolPlaneNoteMessage'
  | 'sessionSelectionToken'
  | 'runSelectionToken'
  | 'toolPlaneRequestToken'
>;

export type ControllerRunStreamState = Pick<
  ShellState,
  | 'selectedSession'
  | 'runs'
  | 'sessions'
  | 'selectedRun'
  | 'eventSource'
  | 'events'
  | 'transcript'
  | 'contextChars'
  | 'undoAvailable'
  | 'undoDetail'
  | 'artifacts'
  | 'approvals'
  | 'checkpoints'
  | 'tools'
  | 'recentSessionsMessage'
  | 'providerSessionLabel'
  | 'runTitleLabel'
  | 'runStatusLabel'
  | 'runStatusClassName'
  | 'runStateNoteMessage'
  | 'runUpdateFeedbackMessage'
  | 'runSelectionToken'
>;

export type ControllerBootstrapState = Pick<
  ShellState,
  | 'toolPlane'
  | 'sessions'
  | 'recentSessionsMessage'
  | 'archiveSessions'
  | 'orchestrationFlows'
  | 'selectedSession'
  | 'selectedRun'
  | 'runs'
  | 'recommendation'
  | 'providerSessionLabel'
  | 'toolPlaneNoteMessage'
  | 'selectedSessionNoteMessage'
  | 'recommendationRequestToken'
  | 'runSelectionToken'
  | 'eventSource'
  | 'events'
  | 'transcript'
  | 'contextChars'
  | 'undoAvailable'
  | 'undoDetail'
  | 'artifacts'
  | 'approvals'
  | 'checkpoints'
  | 'tools'
  | 'runTitleLabel'
  | 'runStatusLabel'
  | 'runStatusClassName'
  | 'runStateNoteMessage'
  | 'runUpdateFeedbackMessage'
  | 'orchestratorNoteMessage'
>;
